name: "Blue Pipeline Run View"
description: |
    The Blue Pipeline allows a user to run CAMR and the ELISA extractor.
data-object: com.artistech.ee.beans.Data
data-dir: /work/Dev/blue-pipeline-web/data
parts:
    input:
        output-dir: input
        requires: []
        page: InputFile
        parameters:
            - parameter:
                name: Text_File
                value: ""
                type: file
    camr:
        output-dir: camr_out
        requires:
            - input
        page: CAMR
        parameters:
            - parameter:
                name: path
                value: /home/matta/Dev/camr
                type: hidden
    elisa:
        output-dir: elisa_out
        requires:
            - camr
        page: Elisa
        parameters: 
            - parameter:
                name: lang
                value: en
                type: select
                values:
                    - en
            - parameter:
                name: model
                value: DNN
                type: select
                values:
                    - DNN
#                    - ExpectD
#                    - CRF
            - parameter:
                name: output_format
                value: KnowledgeGraph
                type: select
                values:
                    - KnowledgeGraph
                    - EvalTab
            - parameter:
                name: url
                value: http://ubuntu-16:3300/elisa_ie
                type: hidden
